version: '3.5'

services:
  db:
    image: postgres:latest
    container_name: db_container
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pizzeria
    volumes:
       - ./database/pizzeria.sql:/docker-entrypoint-initdb.d/pizzeria.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d pizzeria"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s